version: "2.2"
services:
  battleship-server:
    cpus: .4
    mem_limit: 819m
    build:
      context: .
    read_only: true
    environment:
      - PORT=80
      - FLAG=utflag{if_u_want_it_done_right_dont_rely_on_client}
      - CAPTCHA_SECRET=[REDACTED]
    restart: "always"
    networks:
      battleship:
  battleship-frontend:
    image: nginx:stable-alpine
    ports:
      - "9998:80"
    volumes:
      - "./static:/usr/share/nginx/html:ro"
      - "./site.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: "always"
    networks:
      battleship:
networks:
  battleship:
