unstable_features = true # (also unstable)

# stable features
# array_width = 60 # default # controlled by use_small_heuristics
# attr_fn_like_width = 70 # default # controlled by use_small_heuristics
# chain_width = 60 # default # controlled by use_small_heuristics
disable_all_formatting = false # default
# edition = "2021" # obtain edition from Cargo.toml
fn_args_layout = "Tall" # default
# fn_call_width = 60 # default # controlled by use_small_heuristics
force_explicit_abi = true # default
hard_tabs = false # default
match_arm_leading_pipes = "Never" # default
match_block_trailing_comma = true # default
max_width = 100 # default
merge_derives = true # default
newline_style = "Unix"
remove_nested_parens = true # default
reorder_imports = true # default
reorder_modules = true # default
# single_line_if_else_max_width = 50 # default # controlled by use_small_heuristics
# struct_lit_width = 18 # default # controlled by use_small_heuristics
# struct_variant_width = 35 # default # controlled by use_small_heuristics
tab_spaces = 4 # default
use_field_init_shorthand = true
use_small_heuristics = "Default" # default
use_try_shorthand = true

# unstable features
binop_separator = "Back"
blank_lines_lower_bound = 0 # default
blank_lines_upper_bound = 2
brace_style = "SameLineWhere" # default
color = "Auto" # default
combine_control_expr = false
comment_width = 80 # default
condense_wildcard_suffixes = false # default
control_brace_style = "AlwaysSameLine" # default
empty_item_single_line = true # default
enum_discrim_align_threshold = 100
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
force_multiline_blocks = false # default
format_code_in_doc_comments = true
format_generated_files = false # default
format_macro_matchers = true
format_macro_bodies = true # default
format_strings = true
hex_literal_case = "Upper"
hide_parse_errors = false # default
ignore = [] # default
imports_indent = "Block" # default
imports_layout = "Mixed" # default
indent_style = "Block" # default
inline_attribute_width = 0 # default
license_template_path = "" # default
match_arm_blocks = false # default
imports_granularity = "Module" # default
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false # default
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
# required_version = "" # rustfmt version unspecified
skip_children = false # default
space_after_colon = true # default
space_before_colon = false # default
spaces_around_ranges = false # default
struct_field_align_threshold = 100 # default
struct_lit_single_line = false
trailing_comma = "Vertical" # default
trailing_semicolon = true # default
type_punctuation_density = "Wide" # default
version = "Two"
where_single_line = false # default
wrap_comments = true
